language: go

go:
  # Debian/Ubuntu ships with older Go
  - 1.3.3
  # Recent stable Go
  - 1.5.2

install:
  - go get -d -v ./...

script:
  - go test -coverprofile=cover.out -v ./...
  - go tool cover -html=cover.out -o coverage.html
